name: Sphinx Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Set up dependencies
        run: pip install '.[docs]'
      - name: Compile sphinx
        working-directory: .
        run: |
          python -m sphinx-build -M html ./docs ./build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          publish_branch: docs
          exclude_assets: '.github,**/_static/__pycache__,**/_static/__init__.py'
