name: Pytest

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/pytest.yaml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/pytest.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .[tests]

      - name: Run pytest
        run: pytest
