name: Pytest

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/pytest.yaml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/pytest.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --extra tests --dev
      - name: Run pytest
        run: uv run pytest
