name: Ruff Check

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/ruff.yaml"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/ruff.yaml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check src
